<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class KhachHangSeeder extends Seeder
{
    public function run(): void
    {
        $khachHang = [
            [
                'ho_va_ten' => 'Nguyễn Thị G',
                'email' => 'nguyenthig@gmail.com',
                'so_dien_thoai' => '0900111222',
                'password' => '123456',
                'ngay_sinh' => '1999-04-12',
                'avatar' => 'https://png.pngtree.com/png-vector/20201223/ourlarge/pngtree-cute-cartoon-hand-drawn-cow-animal-avatar-vector-png-image_2591528.jpg',
                'created_at' => '2025-06-02',
            ],
            [
                'ho_va_ten' => 'Trần Văn H',
                'email' => 'tranvanh@gmail.com',
                'so_dien_thoai' => '0911002200',
                'password' => '123456',
                'ngay_sinh' => '2001-07-20',
                'avatar' => 'https://if24h.com/wp-content/uploads/2024/10/avatar-cute-hai.jpg',
                'created_at' => '2025-06-02',
            ],
            [
                'ho_va_ten' => 'Lê Thị I',
                'email' => 'lethii@gmail.com',
                'so_dien_thoai' => '0922334455',
                'password' => '123456',
                'ngay_sinh' => '2000-02-28',
                'avatar' => 'https://if24h.com/wp-content/uploads/2024/10/avatar-vo-tri-thu-vi.jpg',
                'created_at' => '2025-06-02',
            ],
            [
                'ho_va_ten' => 'Phạm Văn J',
                'email' => 'phamvanj@gmail.com',
                'so_dien_thoai' => '0933445566',
                'password' => '123456',
                'ngay_sinh' => '1996-09-15',
                'avatar' => 'https://if24h.com/wp-content/uploads/2024/10/hinh-vo-tri-tai-nang.jpg',
                'created_at' => '2025-06-12',
            ],
            [
                'ho_va_ten' => 'Nguyễn Thị K',
                'email' => 'nguyenthik@gmail.com',
                'so_dien_thoai' => '0944556677',
                'password' => '123456',
                'ngay_sinh' => '1995-05-10',
                'avatar' => 'https://tamkytourism.com/wp-content/uploads/2025/02/avatar-vo-tri-9.jpg',
                'created_at' => '2025-06-13',
            ],
            [
                'ho_va_ten' => 'Trần Văn L',
                'email' => 'tranvanl@gmail.com',
                'so_dien_thoai' => '0955667788',
                'password' => '123456',
                'ngay_sinh' => '1997-12-03',
                'avatar' => 'https://jbagy.me/wp-content/uploads/2025/03/hinh-anh-cute-avatar-vo-tri-3.jpg',
                'created_at' => '2025-06-16',
            ],
            [
                'ho_va_ten' => 'Lê Thị M',
                'email' => 'lethim@gmail.com',
                'so_dien_thoai' => '0966778899',
                'password' => '123456',
                'ngay_sinh' => '2002-03-21',
                'avatar' => 'https://tamkytourism.com/wp-content/uploads/2025/02/avatar-vo-tri-17.jpg',
                'created_at' => '2025-06-23',
            ],
            [
                'ho_va_ten' => 'Phạm Văn N',
                'email' => 'phamvann@gmail.com',
                'so_dien_thoai' => '0977889900',
                'password' => '123456',
                'ngay_sinh' => '1994-08-08',
                'avatar' => 'https://avatarvotri.com/wp-content/uploads/2025/04/hinh-avatar-vo-tri-cute.jpg',
                'created_at' => '2025-06-23',
            ],
            [
                'ho_va_ten' => 'Nguyễn Thị O',
                'email' => 'nguyenthio@gmail.com',
                'so_dien_thoai' => '0988990011',
                'password' => '123456',
                'ngay_sinh' => '2000-06-12',
                'avatar' => 'https://m.yodycdn.com/products/anhvotricuteyodyvn25_m3qzikx6b30e6y10cbt.jpg',
                'created_at' => '2025-06-23',
            ],
            [
                'ho_va_ten' => 'Trần Văn P',
                'email' => 'tranvanp@gmail.com',
                'so_dien_thoai' => '0999001122',
                'password' => '123456',
                'ngay_sinh' => '1993-01-17',
                'avatar' => 'https://avatarvotri.com/wp-content/uploads/2025/04/avatar-vo-tri-dep-ngau.jpg',
                'created_at' => '2025-06-30',
            ],
            [
                'ho_va_ten' => 'Nguyễn Thị Q',
                'email' => 'nguyenthiq@gmail.com',
                'so_dien_thoai' => '0902233445',
                'password' => '123456',
                'ngay_sinh' => '1999-10-01',
                'avatar' => 'https://aic.com.vn/wp-content/uploads/2024/10/avatar-vo-tri-meo-99mOYjIu.jpg',
                'created_at' => '2025-06-23',
            ],
            [
                'ho_va_ten' => 'Trần Văn R',
                'email' => 'tranvanr@gmail.com',
                'so_dien_thoai' => '0912333444',
                'password' => '123456',
                'ngay_sinh' => '1998-02-18',
                'avatar' => 'https://cdn2.fptshop.com.vn/unsafe/1920x0/filters:format(webp):quality(75)/avatar_vo_tri_a49436c5de.jpg',
                'created_at' => '2025-06-29',
            ],
            [
                'ho_va_ten' => 'Lê Thị S',
                'email' => 'lethis@gmail.com',
                'so_dien_thoai' => '0922445566',
                'password' => '123456',
                'ngay_sinh' => '1997-07-05',
                'avatar' => 'https://if24h.com/wp-content/uploads/2024/10/hinh-vo-tri-cute-anh.jpg',
                'created_at' => '2025-06-29',
            ],
            [
                'ho_va_ten' => 'Phạm Văn T',
                'email' => 'phamvant@gmail.com',
                'so_dien_thoai' => '0932555666',
                'password' => '123456',
                'ngay_sinh' => '2001-09-22',
                'avatar' => 'https://bloganchoi.com/wp-content/uploads/2024/07/hinh-nen-capybara-38-696x580.jpg',
                'created_at' => '2025-06-30',
            ],
            [
                'ho_va_ten' => 'Nguyễn Thị U',
                'email' => 'nguyenthiu@gmail.com',
                'so_dien_thoai' => '0942667788',
                'password' => '123456',
                'ngay_sinh' => '1996-12-12',
                'avatar' => 'https://cellphones.com.vn/sforum/wp-content/uploads/2023/11/avatar-vo-tri-3.jpg',
                'created_at' => '2025-07-01',
            ],
            [
                'ho_va_ten' => 'Phạm Thị Dung',
                'email' => 'dungpham@gmail.com',
                'so_dien_thoai' => '0934567890',
                'password' => '123456',
                'ngay_sinh' => '1998-03-25',
                'avatar'    => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbs2v0uFR7wdi4pE7aPfJVWYqTYA6TCsjGzw&s',
                'created_at' => '2025-06-02'
            ],
            [
                'ho_va_ten' => 'Nguyễn Văn A',
                'email' => 'nguyenvana@gmail.com',
                'so_dien_thoai' => '0912345678',
                'password' => '123456',
                'ngay_sinh' => '1998-03-25',
                'avatar'    => 'https://vnclass.edu.vn/wp-content/uploads/2025/02/avatar-vo-tri-26.jpg',
                'created_at' => '2025-07-01'
            ],
            [
                'ho_va_ten' => 'Trần Thị B',
                'email' => 'tranthib@gmail.com',
                'so_dien_thoai' => '0945678901',
                'password' => '123456',
                'ngay_sinh' => '1998-03-25',
                'avatar'    => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqHjzlT06c9-tkO9H8bQhNzDu67GadK6o21Q&s',
                'created_at' => '2025-06-12'
            ],
            [
                'ho_va_ten' => 'Lê Văn C',
                'email' => 'levanc@gmail.com',
                'so_dien_thoai' => '0912345678',
                'password' => '123456',
                'ngay_sinh' => '1998-03-25',
                'avatar'    => 'https://jbagy.me/wp-content/uploads/2025/03/Hinh-anh-avatar-chibi-gau-truc-2.jpg',
                'created_at' => '2025-06-12'
            ],
            [
                'ho_va_ten' => 'Nguyễn Thị D',
                'email' => 'nguyenthid@gmail.com',
                'so_dien_thoai' => '0987654321',
                'password' => '123456',
                'ngay_sinh' => '1997-06-15',
                'avatar' => 'https://img.tripi.vn/cdn-cgi/image/width=700,height=700/https://gcs.tripi.vn/public-tripi/tripi-feed/img/474082XUL/avatar-bua-hai-huoc-va-bua-nhat_044337182.jpg',
                'created_at' => '2025-06-12'
            ],
            [
                'ho_va_ten' => 'Trần Minh E',
                'email' => 'tranminhe@gmail.com',
                'so_dien_thoai' => '0901234567',
                'password' => '123456',
                'ngay_sinh' => '1995-11-08',
                'avatar' => 'https://live.staticflickr.com/4029/35667852906_6ffb006961_m.jpg',
                'created_at' => '2025-07-01'
            ],
            [
                'ho_va_ten' => 'Phạm Quỳnh F',
                'email' => 'phamquynhf@gmail.com',
                'so_dien_thoai' => '0934567890',
                'password' => '123456',
                'ngay_sinh' => '2000-01-30',
                'avatar' => 'https://tophinhanh.net/wp-content/uploads/2024/01/avatar-maruko-cute-2.jpg',
                'created_at' => '2025-06-29'
            ],
            [
                'ho_va_ten' => 'Trần Văn V',
                'email' => 'tranvanv@gmail.com',
                'so_dien_thoai' => '0908777666',
                'password' => '123456',
                'ngay_sinh' => '1999-03-15',
                'avatar' => 'https://png.pngtree.com/png-vector/20191027/ourmid/pngtree-cute-wolf-avatar-with-a-yellow-background-png-image_1873506.jpg',
                'created_at' => '2025-06-12',
            ],
            [
                'ho_va_ten' => 'Nguyễn Thị W',
                'email' => 'nguyenthiw@gmail.com',
                'so_dien_thoai' => '0919888777',
                'password' => '123456',
                'ngay_sinh' => '2000-08-21',
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpZY_s2J1wf1jFko6cvIZAqsjuIGfTQdfJjA&s',
                'created_at' => '2025-06-12',
            ],
            [
                'ho_va_ten' => 'Lê Văn X',
                'email' => 'levanx@gmail.com',
                'so_dien_thoai' => '0929777666',
                'password' => '123456',
                'ngay_sinh' => '1998-07-07',
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSbVHETUO1t6v_nb-7fuMTbHAVOP1zf6koLg&s',
                'created_at' => '2025-06-12',
            ],
            [
                'ho_va_ten' => 'Phạm Thị Y',
                'email' => 'phamthiy@gmail.com',
                'so_dien_thoai' => '0939666555',
                'password' => '123456',
                'ngay_sinh' => '1997-02-28',
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_rS-7D2y1Rh8njxtReQ4g3Afao8iEr6SHlA&s',
                'created_at' => '2025-06-13',
            ],
            [
                'ho_va_ten' => 'Ngô Văn Z',
                'email' => 'ngovanz@gmail.com',
                'so_dien_thoai' => '0949555444',
                'password' => '123456',
                'ngay_sinh' => '2001-11-14',
                'avatar' => 'https://m.yodycdn.com/products/anhvotricuteyodyvn5_m3qzhq75c9l8j2ymfo.jpg',
                'created_at' => '2025-06-13',
            ],
            [
                'ho_va_ten' => 'Hoàng Thị AA',
                'email' => 'hoangthiaa@gmail.com',
                'so_dien_thoai' => '0959444333',
                'password' => '123456',
                'ngay_sinh' => '1995-09-30',
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTApBTQNOxendzx-mpRwwwJUMuFw09DiZt7ug&s',
                'created_at' => '2025-06-13',
            ],
            [
                'ho_va_ten' => 'Đặng Văn BB',
                'email' => 'dangvanbb@gmail.com',
                'so_dien_thoai' => '0969333222',
                'password' => '123456',
                'ngay_sinh' => '1994-04-04',
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA5W8mmdqgticBgvZuCKQ30R7Tez2grRh9fA&s',
                'created_at' => '2025-06-16',
            ],
            [
                'ho_va_ten' => 'Phan Thị CC',
                'email' => 'phanthicc@gmail.com',
                'so_dien_thoai' => '0979222111',
                'password' => '123456',
                'ngay_sinh' => '1996-05-19',
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQE84ZkAzHiXWkFTmCj7wCW2wmoSVweoOG95A&s',
                'created_at' => '2025-06-16',
            ],
            [
                'ho_va_ten' => 'Lý Văn DD',
                'email' => 'lyvandd@gmail.com',
                'so_dien_thoai' => '0989111000',
                'password' => '123456',
                'ngay_sinh' => '1993-03-03',
                'avatar' => 'https://vnclass.edu.vn/wp-content/uploads/2025/02/avatar-vo-tri-2.jpg',
                'created_at' => '2025-06-16',
            ],
            [
                'ho_va_ten' => 'Tạ Thị EE',
                'email' => 'tathiee@gmail.com',
                'so_dien_thoai' => '0999000111',
                'password' => '123456',
                'ngay_sinh' => '2000-10-25',
                'avatar' => 'https://i.pinimg.com/736x/56/72/d6/5672d634f75f75edb6e8cd3de03f099e.jpg',
                'created_at' => '2025-06-16',
            ],

        ];
        DB::table('khach_hangs')->truncate();
        DB::table('khach_hangs')->delete();
        DB::table('khach_hangs')->insert($khachHang);
    }
}
